### ISSUE TITLE
 no such file or directory, open

### ISSUE THREAD

**Issue by merolaika** [ChetanXpro/short-video-automation#70]
Hello, i get this error;

`Error in createShortScript:  Error: ENOENT: no such file or directory, open 'C:\Users\chetan\Developer\code\short-video-automation\basicaudio.wav.vtt'
    at Object.readFileSync (node:fs:453:20)
    at generateYoutubeShort (C:\ai_dosya\short-video-automation\src\index.ts:31:5)
    at Object.<anonymous> (C:\ai_dosya\short-video-automation\src\index.ts:87:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module.m._compile (C:\ai_dosya\short-video-automation\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Object.require.extensions.<computed> [as .ts] (C:\ai_dosya\short-video-automation\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\chetan\\Developer\\code\\short-video-automation\\basicaudio.wav.vtt'`

**Comment by ChetanXpro** [comment]
Will push fix for this soon, there is some hard coded paths there, will remove them
